/** Category emoji used for generated listing covers. Extend freely. */
export const CATEGORY_EMOJI: Record<string, string> = {
  tools: "🔧",
  garden: "🌿",
  home: "🛋️",
  kitchen: "🍳",
  electronics: "🔌",
  sports: "🏅",
  outdoor: "⛺",
  "party-events": "🎉",
  mobility: "🚲",
  "kids-family": "🧸",
  "other-product": "📦",
  "home-diy": "🛠️",
  "garden-service": "🌻",
  "it-tech": "💻",
  education: "📚",
  languages: "🗣️",
  pets: "🐕",
  transport: "🚚",
  events: "🎪",
  creative: "🎨",
  consulting: "💡",
  "everyday-help": "🤝",
  "other-service": "✨",
};

export const PRODUCT_CATEGORIES = [
  { slug: "tools", name: "Tools" },
  { slug: "garden", name: "Garden" },
  { slug: "home", name: "Home" },
  { slug: "kitchen", name: "Kitchen" },
  { slug: "electronics", name: "Electronics" },
  { slug: "sports", name: "Sports" },
  { slug: "outdoor", name: "Outdoor" },
  { slug: "party-events", name: "Party & Events" },
  { slug: "mobility", name: "Mobility" },
  { slug: "kids-family", name: "Kids & Family" },
  { slug: "other-product", name: "Other" },
];

export const SERVICE_CATEGORIES = [
  { slug: "home-diy", name: "Home & DIY" },
  { slug: "garden-service", name: "Garden" },
  { slug: "it-tech", name: "IT & Technology" },
  { slug: "education", name: "Education" },
  { slug: "languages", name: "Languages" },
  { slug: "pets", name: "Pets" },
  { slug: "transport", name: "Transport" },
  { slug: "events", name: "Events" },
  { slug: "creative", name: "Creative" },
  { slug: "consulting", name: "Consulting" },
  { slug: "everyday-help", name: "Everyday Help" },
  { slug: "other-service", name: "Other" },
];
